Blog/blog_posts/forms.py
#Blog_posts/froms.py

from turtle import title
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

Blog/blog_posts/views.py
#Blog_posts/views.py

from os import abort
from flask import redirect, render_template, request, url_for,flash, Blueprint
from flask_login import current_user, login_required

from Blog import db
from Blog.models import BlogPost
from Blog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

#CREATE
@blog_posts.route('/create', methods=['GET', 'POST'])
def create_post():

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created!",'success')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)

    


#BLOG POST(READ)
@blog_posts.route('/<int:blog_post_id>', methods=['GET', 'POST'])
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title,date=blog_post.date, post=blog_post )


#UPDATE
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    
    if blog_post.author != current_user:
        abort(403)
    
    form = BlogPostForm()
    if form.validate_on_submit():

        blog_post.title=form.title.data
        blog_post.text=form.text.data
        db.session.commit()
        flash("Blog Post Updated! ")
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    elif request.method == "GET":
        blog_post.title=form.title.data
        blog_post.text=form.text.data
    return render_template('create_post.html', title='Updating', form=form)


#DELETE
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    
    if blog_post.author != current_user:
        abort(403)
    
    db.session.delete(blog_post)
    db.session.commit()
    flash("Blog Post Deleted!", 'success')
    return redirect(url_for('core.index'))

Blog/core/views.py
#core/views.py

from flask import render_template, request, Blueprint

from Blog.blog_posts.views import blog_post
from Blog.models import BlogPost

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=3)

    return render_template('index.html', blog_posts=blog_posts)

@core.route('/info/')
def info():
    return render_template('info.html')

Blog/users/views.py
# users/views.py

from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required, logout_user, login_user

from Blog import db
from Blog.models import User, BlogPost
from Blog.users.forms import LoginForm, RegisterFrom, UpdateUserForm
from Blog.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterFrom()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Registraion Successful!",'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Logged in successfully', "success" )

            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)

    return render_template('/login.html', form=form)


# logout
@users.route('/logout')
def logout():
    logout_user()
    flash('Logged out Successfully!', 'success')
    return redirect(url_for('core.index'))

# account
@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    
    form = UpdateUserForm()

    if form.validate_on_submit():  
        if form.username.data and form.username.data != current_user.username:
            current_user.username = form.username.data

        if form.email.data and form.email.data != current_user.email:
            current_user.email = form.email.data
     
        if form.picture.data:
            pic = add_profile_pic(form.picture.data, current_user.username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!', 'success')
        return redirect(url_for('core.index'))

            
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form = form)


# user blog lists
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts= BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts,user=user)

Blog/templates/account.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container mt-3">
    <div class="mt-4 p-5 bg-primary text-white rounded text-center">
        <h1>Welcome to page {{ current_user.username }}</h1>
        <img src="{{ url_for('static', filename='profile_pics/'+ current_user.profile_image) }}" alt="" width="200px" height="200px">
    </div>
</div>


  <div class="container">
    <form method="POST" enctype="multipart/form-data">
      {{ form.hidden_tag() }} 
      <div class="form-group">
          {{ form.username.label(class="form-group")}} {{ form.username(class="form-control")}}
      </div>
      <div class="form-group">
          {{ form.email.label(class="form-group") }} {{ form.email(class="form-control") }}
      </div>
      <div class="form-group">
          {{ form.picture.label(class="form-group") }} {{form.picture(class="form-control") }} 
      <div class="form-group">
      </div>
      <div class="form-group">
          {{form.submit(class="btn btn-success btn-block")}}
      </div>
    </form>
  </div>
{% endblock %}

Blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %}BLOG ME | Write your freedom words{% endblock %}</title>
</head>

<body>

    <!-- NAVBAR-->
    <nav class="navbar navbar-expand-lg py-3 navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{{ url_for('core.index')}}" class="navbar-brand">
                <!-- Logo Image -->
                <img src="https://bootstrapious.com/i/snippets/sn-nav-logo/logo.png" width="45" alt=""
                    class="d-inline-block align-middle mr-2">
                <!-- Logo Text -->
                <span class="text-uppercase font-weight-bold">BLOG ME</span>
            </a>

            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>

            <div id="navbarSupportedContent" class="collapse navbar-collapse justify-content-end">
                <!-- Links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.index')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('core.info')}}">About</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog_posts.create_post') }}">Create post</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block body_block %}

    {% endblock %}


</body>

</html>

Blog/templates/blog_post.html
{% extends 'base.html' %}

{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>{{ post.title }}</h1>
        <h2>Written By: {{ post.author.username }}</h2>
        <p>{{ post.text }}</p>
        <h3>Published on: {{ post.date.strftime('%B %d, %Y') }}</h3>
    </div>
    {% if post.author == current_user %}
    <a href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#del_modal" name="button">
        Delete</button>
    {% endif %}
</div>


<!-- The Modal -->
<div class="modal" id="del_modal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Delete Post</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <p>Are you want to sure delete the post?</p>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}">
                    <input type="submit" class="btn btn-outline-dark" value="Delete">
                </form>
            </div>

        </div>
    </div>
</div>


{% endblock %}

Blog/templates/create_post.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
    <form class="form-group" method="post">
        {{ form.hidden_tag() }} 
        <div class="form-group">
            {{ form.title.label(class="form-group")}} {{ form.title(class="form-control")}}
        </div>
        <div class="form-group">
            {{ form.text.label(class="form-group") }} {{form.text(class="form-control") }} 
        </div>
        <br>
        <div class="form-group">
            {{form.submit(class="btn btn-success btn-block")}}
        </div>
    </form>
</div>
{% endblock %}

Blog/templates/index.html
{% extends 'base.html' %}

{% block body_block %}

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="container">
    <div class="jumbotron">
        <h1 class="display-3">Blog Post</h1>
        <p class="lead">container-fluid</p>
        <hr class="my-2">
        <p>More info</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button">Jumbo action name</a>
        </p>
    </div>
</div>

<div class="container">
    {% for post in blog_posts.items %}
    <div class="card">
        <div class="card-body">
            <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="card-title">{{ post.title }}</a></h2>
            <p class="card-text">{{ post.text }}</p>
            Written By: <a href="{{ url_for('users.user_posts',username=post.author.username) }}" class="card-link">{{ post.author.username }}</a>
            <p class="text-muted">Published On: {{ post.date.strftime("%Y-%m-%d") }}</p>
            <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-outline-primary">Read Blog Post</a>
        </div>
    </div>
    {% endfor %}
</div>



<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for( 'core.index',page=page_num )}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for( 'core.index',page=page_num )}}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>


{% endblock %}

Blog/templates/login.html
{% extends 'base.html' %}

{% block body_block %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

    <div class="login-page bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <h3 class="mb-3">Login Now</h3>
                    <div class="bg-white shadow rounded">
                        <div class="row">
                            <div class="col-md-7 pe-0">
                                <div class="form-left h-100 py-5 px-5">
                                    <form action="" class="row g-4" method="POST">
                                        {{ form.hidden_tag() }}
                                        <div class="col-12">
                                            {{ form.email.label(class="form-group")}}
                                            <div class="input-group">
                                                <div class="input-group-text"><i class="bi bi-person-fill"></i></div>
                                                {{ form.email(class="form-control", placeholder="Enter your email")}}
                                            </div>
                                        </div>

                                        <div class="col-12">
                                            {{ form.password.label(class="form-group")}}
                                            <div class="input-group">
                                                <div class="input-group-text"><i class="bi bi-lock-fill"></i></div>
                                                {{ form.password(class="form-control", placeholder="Enter your password")}}
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            {{form.submit(class="btn btn-outline-dark px-4 float-end mt-4")}}
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-5 ps-0 d-none d-md-block">
                                <div class="form-right h-100 bg-dark text-white text-center pt-5">
                                    <img src="{{ url_for('static', filename='images/side.png') }}" alt="" width="250px">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


<!-- 


    <form method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class="form-group")}} {{ form.email(class="form-control")}}
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-group") }} {{form.password(class="form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{form.submit(class="btn btn-success btn-block")}}
        </div>
    </form> -->

{% endblock %}

Blog/templates/register.html
{% extends 'base.html' %} {% block body_block %}
<div class="container">
  <form method="post">
    {{ form.hidden_tag() }} 
    <div class="form-group">
        {{ form.email.label(class="form-group")}} {{ form.email(class="form-control")}}
    </div>
    <div class="form-group">
        {{ form.username.label(class="form-group") }} {{ form.username(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.password.label(class="form-group") }} {{form.password(class="form-control") }} 
    <div class="form-group">
    </div>
    <div class="form-group">
        {{ form.pass_confirm.label(class="form-group") }} {{ form.pass_confirm(class="form-control") }} 
    </div>
    <div class="form-group">
        {{form.submit(class="btn btn-success btn-block")}}
    </div>
  </form>
</div>
{% endblock %}

Blog/templates/user_blog_posts.html
{% extends 'base.html' %}

{% block body_block %}
<div class="jumbotron">
    <div align="center">
        <h1>Welcom to page {{ user.username }}</h1>
        <img align='center' src="{{ url_for('static', filename='profile_pics/'+current_user.profile_image) }}" alt="">
    </div>
</div>

{% for post in blog_posts.items %}
<h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
written By: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author }}</a>
<p class="text-muted">Published On: {{ post.date.strftime("%Y-%m-%d") }}</p>
<br>
{{ post.text }}
<br>
{% endfor %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ post_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ post_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>


{% endblock %}